os:
  - linux
  - osx

language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.2

    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

    - os: linux
      dist: trusty
      env: UNIT_TESTS=true LLVM_VERSION=3.9.0 BOOST_VERSION=default ENABLE_MEMCHECK=true
      compiler: gcc

before_install:
#    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    #- if [ "$CXX" == "clang++" -a "$CPP14" == "0" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get upgrade          ; fi

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle   ; fi

install:
    # g++ 4.9
#    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
#    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

    ## clang 3.5
    #- if [ "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5; fi
    #- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - cd build
    - make

notifications:
    email:
    - neveralso@qq.com

