name: ubuntu
on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}-libjstack-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            triplet: x64-linux
            generator: Unix Makefiles

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Start Pg
        shell: bash
        run: sudo systemctl start postgresql.service

      - name: Test Pg
        shell: bash
        run: sudo -u postgres psql -d postgres -c "SELECT 1"

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Install dependencies
        shell: bash
        run: sudo apt-get install libboost-filesystem-dev libboost-system-dev libboost-test-dev libssl-dev libpq-dev libpqtypes-dev postgresql-server-dev-all libcurl4-openssl-dev

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER="/usr/bin/gcc-10" -DCMAKE_CXX_COMPILER="/usr/bin/g++-10" ${{ github.workspace }}

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: ctest -C $BUILD_TYPE
